### ISSUE TITLE
anaconda issue

### ISSUE THREAD

**Issue by palemcorestrat** [palemcorestrat/anacond-issue#1]
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\app\main.py", line 19, in <module>
    from anaconda_navigator.app.start import start_app
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\app\start.py", line 30, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 45, in <module>
    from anaconda_navigator.widgets.dialogs.login import TeamEditionAddChannelsPage
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\widgets\dialogs\login\__init__.py", line 17, in <module>
    from .cloud_dialogs import *
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\widgets\dialogs\login\cloud_dialogs.py", line 21, in <module>
    from anaconda_navigator.api import cloud
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\api\cloud\__init__.py", line 4, in <module>
    from .api import *
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_navigator\api\cloud\api.py", line 17, in <module>
    import anaconda_cloud_auth.handlers
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_cloud_auth\__init__.py", line 6, in <module>
    from anaconda_cloud_auth.actions import login  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_cloud_auth\actions.py", line 16, in <module>
    from anaconda_cloud_auth.config import APIConfig
  File "C:\Users\LENOVO\anaconda3\Lib\site-packages\anaconda_cloud_auth\config.py", line 8, in <module>
    from pydantic import BaseSettings
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages\pydantic\__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages\pydantic\_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error

**Comment by palemcorestrat** [comment]
please try to solve
